language: java

jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

before_cache:
  -'$HOME/.m2/repository'
  -'$HOME/.gradle'
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - bogung1207@naver.com